name: "commit-master-zip"

on:
  push:
    branches: 
    - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: compress function files or director to zip file
      run: zip -j index-py.zip ./python-sample/index.py

    - name: deploy compress zip function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: functiongraph.cn-north-4.myhuaweicloud.com
        project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
        function_codetype: zip
        function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:func-dir2:latest
        function_file: ./index-py.zip