name: "commit-master-file"

on:
  push:
    branches: 
    - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: deploy single function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: functiongraph.cn-north-4.myhuaweicloud.com
        project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
        function_codetype: file
        function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:func-lizy-py3:latest
        function_file: ./target/func-py3.py

