name: "commit-master-obs"

on:
  push:
    branches: 
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    # jar包比较大，先上传到OBS
    - name: Upload To Huawei OBS
      uses: huaweicloud/obs-helper@v1.0.0
      id: upload_file_to_obs
      with:
        access_key: ${{ secrets.ACCESSKEY }}
        secret_key: ${{ secrets.SECRETACCESSKEY }}
        bucket_name: obs-lizy20220702
        operation_type: upload
        local_file_path: target/func-lizy2_latest.zip
        obs_file_path: function/functionj/v1.0.0.1/    

    #通过OBS部署函数
    - name: deploy OBS function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: functiongraph.cn-north-4.myhuaweicloud.com
        project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
        function_codetype: obs
        function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:func-lizy2:latest
        function_file: https://obs-lizy20220702.obs.cn-north-4.myhuaweicloud.com/function/functionj/v1.0.0.1/func-lizy2_latest.zip