name: "commit-master-jar"

on:
  push:
    branches:
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

          # 完成java项目打包
      - name: build maven project
        run: |
          cd java-sample/functionj
          mvn clean -U package -Dmaven.test.skip

      - name: deploy java jar to huaweicloud functiongraph
        uses: huaweicloud/deploy-functiongraph-action@v1.0
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          endpoint: functiongraph.cn-north-4.myhuaweicloud.com
          project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
          function_codetype: jar
          function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:func-lizy-java8:latest
          function_file: ./target/func-java-1.0.jar